#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import os
import click
import aws_lambda
import logging

CURRENT_DIR = os.getcwd()

logging.getLogger('pip').setLevel(logging.CRITICAL)


@click.group()
def cli():
    pass


@click.command(help="Create a new function for Lambda.")
@click.argument('folder', nargs=-1, type=click.Path(file_okay=False, writable=True))
def init(folder):
    path = CURRENT_DIR
    if len(folder) > 0:
        path = "{}/{}".format(CURRENT_DIR, folder[0])
        if not os.path.exists(path):
            os.makedirs(path)
    aws_lambda.init(path)


@click.command(help="Run a local test of your function.")
@click.option('--event-file', default=None, help='Alternate event file.')
@click.option('--verbose', '-v', is_flag=True)
def invoke(event_file, verbose):
    aws_lambda.invoke(CURRENT_DIR, event_file, verbose)


if __name__ == '__main__':
    cli.add_command(init)
    cli.add_command(invoke)
    cli()
